#ifndef MICROPY_INCLUDED_SHARED_BINDINGS_RAMBUS___INIT___H
#define MICROPY_INCLUDED_SHARED_BINDINGS_RAMBUS___INIT___H


// Nothing now.


#endif  // MICROPY_INCLUDED_SHARED_BINDINGS_MYMODULE___INIT___H